### ISSUE TITLE
Disabling Gutenburg via theme config

### ISSUE THREAD

**Issue by arrubakook** [eighteen73/pulsar#7]
There are times when the Gutenburg editor is not necessary and falling back to the classic editor is preferred.

We can utilise the `use_block_editor_for_post_type` filter to disable the editor per post type.

Hooking this filter up to a config file e.g. /pulsar/config/gutenburg.php might be a useful feature to carry over to new projects.

**Comment by brettsmason** [comment]
I'm going to close this as we plan on moving post type registration into Nebula, and it can be controlled per class with the options available for https://github.com/johnbillion/extended-cpts 😄
